services:
  app:
    image: ${REGISTRY}/${REGISTRY_NS}/${APP_NAME}:${IMAGE_TAG}
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    volumes:
      - ${APPDATA_ROOT}/${APP_NAME}/data:/app/data
    networks:
      - default
      - dokploy-network
    logging:
      driver: json-file
      options:
        max-size: ${LOG_MAX_SIZE}
        max-file: ${LOG_MAX_FILE}

networks:
  dokploy-network:
    external: true
