services:
  zot:
    image: ghcr.io/project-zot/zot-linux-amd64:${ZOT_VERSION:-v2.1.20}
    container_name: zot
    restart: unless-stopped

    ports:
      - "10.8.0.1:5000:5000"

    volumes:
      - ./config.json:/etc/zot/config.json:ro
      - /srv/registry/htpasswd:/etc/zot/htpasswd:ro
      - /srv/registry/data:/var/lib/registry

    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"
